# -*- coding: utf-8 -*-
# Copyright 2023 Red Hat
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import absolute_import, division, print_function

__metaclass__ = type

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the
# cli_rm_builder.
#
# Manually editing this file is not advised.
#
# To update the argspec make the desired changes
# in the module docstring and re-run
# cli_rm_builder.
#
#############################################

"""
The arg spec for the ios_l2vpn_evpn_ptp module
"""


class L2vpn_evpn_ptpArgs(object):  # pylint: disable=R0903
    """The arg spec for the ios_l2vpn_evpn_ptp module
    """

    argument_spec = {
        "config": {
            "type": "list",
            "elements": "dict",
            "options": {
                "instance": {"type": "str", "required": True},
                "auto_route_target": {"type": "bool", "default": True},
                "rd": {"type": "str"},
                "route_target_import": {"type": "list", "elements": "str"},
                "route_target_export": {"type": "list", "elements": "str"},
                "vpws_context": {
                    "type": "list",
                    "elements": "dict",
                    "options": {
                        "context": {"type": "str", "required": True},
                        "service": {
                            "type": "dict",
                            "required_together": [["target", "source"]],
                            "options": {
                                "target": {"type": "str"},
                                "source": {"type": "str"},
                            },
                        },
                        "member": {"type": "str"},
                        "remote_link_failure_notification": {"type": "bool"},
                        "shutdown": {"type": "bool"},
                    },
                },
            },
        },
        "running_config": {"type": "str"},
        "state": {
            "type": "str",
            "choices": [
                "merged",
                "replaced",
                "deleted",
                "rendered",
                "parsed",
                "gathered",
            ],
            "default": "merged",
        },
    }  # pylint: disable=C0301
